language: node_js
node_js:
  - "0.8"
  - "0.10"

before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8"  ] || npm install -g npm@1.4.28'

before_script:
  - npm install -g grunt-cli

script:
  - grunt
