// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      pkgFile: 'package.json',
      files: {
        source: ['lib/**/*.js']
      },
      simplemocha: {
        options: {
          ui: 'bdd',
          reporter: 'dot'
        },
        unit: {
          src: ['test/**/*.spec.coffee']
        }
      },
      jshint: {
        source: {
          files: {
            src: '<%= files.source %>'
          },
          options: {
            node: true,
            strict: false
          }
        },
        options: {
          quotmark: 'single',
          camelcase: true,
          strict: true,
          trailing: true,
          curly: true,
          eqeqeq: true,
          immed: true,
          latedef: true,
          newcap: true,
          noarg: true,
          sub: true,
          undef: true,
          boss: true,
          globals: {}
        }
      },
      'npm-contributors': {
        options: {
          commitMessage: 'chore: update contributors'
        }
      },
      bump: {
        options: {
          commitMessage: 'chore: release v%VERSION%',
          pushTo: 'upstream'
        }
      }
    });
    grunt.loadNpmTasks('grunt-simple-mocha');
    grunt.loadNpmTasks('grunt-contrib-jshint');
    grunt.loadNpmTasks('grunt-npm');
    grunt.loadNpmTasks('grunt-bump');
    grunt.loadNpmTasks('grunt-auto-release');
    grunt.registerTask('default', ['jshint', 'test']);
    grunt.registerTask('test', ['simplemocha:unit']);
    return grunt.registerTask('release', 'Build, bump and publish to NPM.', function(type) {
      return grunt.task.run(['npm-contributors', "bump:" + (type || 'patch'), 'npm-publish']);
    });
  };

}).call(this);
